In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
model1=LinearRegression()
model2=LinearRegression()
model3=LinearRegression()
model4=LinearRegression()

In [2]:
df1=pd.read_csv("domestic_foreign_visitors_hyderabad_prediction.csv")
df1

district  year  domestic_total_visitor_every_year   
0  Hyderabad  2016                           23394705  \
1  Hyderabad  2017                           27160242   
2  Hyderabad  2018                           19543651   
3  Hyderabad  2019                           13802362   

   foreign_total_visitor_every_year  
0                            163631  
1                            247179  
2                            314788  
3                            319300

In [3]:
df1['domestic_growth_rate']=df1['domestic_total_visitor_every_year'].pct_change()
df1['foreign_growth_rate']=df1['foreign_total_visitor_every_year'].pct_change()
df1['domestic_growth_rate'] = df1['domestic_growth_rate'].replace(np.nan, 0)
df1['foreign_growth_rate'] = df1['foreign_growth_rate'].replace(np.nan, 0)
df1['domestic_total_visitor_every_year_log']=np.log10(df1['domestic_total_visitor_every_year'])
df1['foreign_total_visitor_every_year_log']=np.log10(df1['foreign_total_visitor_every_year'])
df1

district  year  domestic_total_visitor_every_year   
0  Hyderabad  2016                           23394705  \
1  Hyderabad  2017                           27160242   
2  Hyderabad  2018                           19543651   
3  Hyderabad  2019                           13802362   

   foreign_total_visitor_every_year  domestic_growth_rate   
0                            163631              0.000000  \
1                            247179              0.160957   
2                            314788             -0.280432   
3                            319300             -0.293767   

   foreign_growth_rate  domestic_total_visitor_every_year_log   
0             0.000000                               7.369118  \
1             0.510588                               7.433934   
2             0.273522                               7.291006   
3             0.014333                               7.139953   

   foreign_total_visitor_every_year_log  
0                              5.213866  
1                              5.393012  
2                              5.498018  
3                              5.504199

In [8]:
#for domestic
model1.fit(df1[['year']],df1['domestic_growth_rate'])

LinearRegression()

In [17]:
model1.predict([[2025]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-1.09532872])

In [6]:
model2.fit(df1[['year','domestic_growth_rate']],df1['domestic_total_visitor_every_year_log'])

LinearRegression()

In [18]:
model2.predict([[2025,-1.09532872]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.68568727])

In [12]:
domestic_population=4,850,582

In [19]:
#for foreign
model3.fit(df1[['year']],df1['foreign_growth_rate'])

LinearRegression()

In [37]:
model3.predict([[2025]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.05406214])

In [30]:
model4.fit(df1[['year','foreign_growth_rate']],df1['foreign_total_visitor_every_year_log'])

LinearRegression()

In [38]:
model4.predict([[2025,0.05406214]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.13427851])

In [17]:
foreign_population=1362318

In [19]:
df2={'year': [2025, 2025], 'tourists': ['domestic', 'foreign'],'predicted_visitor':[4850582,1362318]}

df3 = pd.DataFrame(data=df2)
df3

year  tourists  predicted_visitor
0  2025  domestic            4850582
1  2025   foreign            1362318

In [20]:
df3.to_csv("hyderabad_domestic_foreign_predicted_visitors_2025.csv")