In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
model1=LinearRegression()
model2=LinearRegression()

In [2]:
df1=pd.read_csv("domestic_foreign_revenue.csv")
df1

district  year  domestic_total_visitor_every_year   
0  Hyderabad  2016                           23394705  \
1  Hyderabad  2017                           27160242   
2  Hyderabad  2018                           19543651   
3  Hyderabad  2019                           13802362   

   domestic_average_revenue  foreign_total_visitor_every_year   
0              387697051260                            163631  \
1              450099530424                            247179   
2              323877384372                            314788   
3              228732743064                            319300   

   foreign_average_revenue  
0               2711692932  
1               4096250388  
2               5216666736  
3               5291439600

In [3]:
df1['domestic_average_revenue_log']=np.log10(df1['domestic_average_revenue'])
df1['foreign_average_revenue_log']=np.log10(df1['foreign_average_revenue'])
df1

district  year  domestic_total_visitor_every_year   
0  Hyderabad  2016                           23394705  \
1  Hyderabad  2017                           27160242   
2  Hyderabad  2018                           19543651   
3  Hyderabad  2019                           13802362   

   domestic_average_revenue  foreign_total_visitor_every_year   
0              387697051260                            163631  \
1              450099530424                            247179   
2              323877384372                            314788   
3              228732743064                            319300   

   foreign_average_revenue  domestic_average_revenue_log   
0               2711692932                     11.588492  \
1               4096250388                     11.653309   
2               5216666736                     11.510381   
3               5291439600                     11.359328   

   foreign_average_revenue_log  
0                     9.433241  
1                     9.612386  
2                     9.717393  
3                     9.723574

In [5]:
#for domestic
model1.fit(df1[['year','domestic_total_visitor_every_year']],df1['domestic_average_revenue_log'])

LinearRegression()

In [7]:
#2025 domestic visitors=4850582

model1.predict([[2020,12615297]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.3354586])

In [8]:
model1.predict([[2021,10419705]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.28210715])

In [9]:
model1.predict([[2022,8606238]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.23661397])

In [10]:
model1.predict([[2023,7108391]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.19761139])

In [11]:
model1.predict([[2024,5871232]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.16396976])

In [12]:
model1.predict([[2025,4850582]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.13478056])

In [13]:
#for foreign

model2.fit(df1[['year','foreign_total_visitor_every_year']],df1['foreign_average_revenue_log'])

LinearRegression()

In [14]:
#2025 foreign visitor=1362318

model2.predict([[2020,442868]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.9653612])

In [15]:
model2.predict([[2021,554467]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.1837579])

In [16]:
model2.predict([[2022,694187]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.46058353])

In [17]:
model2.predict([[2023,869114]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.81056115])

In [18]:
model2.predict([[2024,1088122]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.25212887])

In [19]:
model2.predict([[2025,1362318]])

C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.80836447])